apiVersion: v1
kind: Service
metadata:
  name: {{ include "mtgmods-license.fullname" . }}-redis
  labels:
    {{- include "mtgmods-license.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "mtgmods-license.componentLabels" (dict "Release" .Release "Chart" .Chart "Values" .Values "component" "redis") | nindent 4 }}
  ports:
    - name: redis
      port: {{ .Values.redis.port }}
      targetPort: redis
