apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mtgmods-license.fullname" . }}-redis
  labels:
    {{- include "mtgmods-license.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.redis.replicaCount }}
  selector:
    matchLabels:
      {{- include "mtgmods-license.componentLabels" (dict "Release" .Release "Chart" .Chart "Values" .Values "component" "redis") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mtgmods-license.componentLabels" (dict "Release" .Release "Chart" .Chart "Values" .Values "component" "redis") | nindent 8 }}
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.image | quote }}
          args: ["redis-server", "--save", "", "--appendonly", "no"]
          ports:
            - name: redis
              containerPort: {{ .Values.redis.port }}
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 10
            periodSeconds: 10
