{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mtgmods-license.fullname" . }}-secrets
  labels:
    {{- include "mtgmods-license.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.secrets.postgresUser | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
  POSTGRES_DB: {{ .Values.secrets.postgresDatabase | quote }}
  DATABASE_URL: {{ printf "postgresql+asyncpg://%s:%s@%s-postgres:%v/%s" .Values.secrets.postgresUser .Values.secrets.postgresPassword (include "mtgmods-license.fullname" .) .Values.postgres.port .Values.secrets.postgresDatabase | quote }}
  DATABASE_POSTGRES_URL: {{ printf "postgresql+asyncpg://%s:%s@%s-postgres:%v/%s" .Values.secrets.postgresUser .Values.secrets.postgresPassword (include "mtgmods-license.fullname" .) .Values.postgres.port .Values.secrets.postgresDatabase | quote }}
  RABBITMQ_URL: {{ .Values.secrets.rabbitmqUrl | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  BOT_SECRET_TOKEN: {{ .Values.secrets.botSecretToken | quote }}
  INTERNAL_SECRET_TOKEN: {{ .Values.secrets.internalSecretToken | quote }}
{{- end }}
