apiVersion: v1
kind: Service
metadata:
  name: {{ include "mtgmods-license.fullname" . }}
  labels:
    {{- include "mtgmods-license.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "mtgmods-license.componentLabels" (dict "Release" .Release "Chart" .Chart "Values" .Values "component" "api") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
